<a href="https://colab.research.google.com/github/jaworskamalgorzata99-GIT/Maching-Learning-Bootcamp/blob/main/supervised/01_basics/01_linear_regression_normal_equation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
! pip install scikit-learn

In [2]:
!pip install --upgrade scikit-learn

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.5/9.5 MB 48.8 MB/s eta 0:00:00
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 1.6.1
    Uninstalling scikit-learn-1.6.1:
      Successfully uninstalled scikit-learn-1.6.1


### Spis treści:
1. [Import bibliotek](#0)
2. [Przygotowanie danych](#1)
3. [Równanie normalne](#2)
4. [Regresja liniowa przy pomocy scikit-learn](#3)

###<a name='0'></a> Import bibliotek

In [3]:
import numpy as np

###<a name='1'></a> Przygotowanie danych

In [4]:
X1 = np.array([1,2,3,4,5,6])
Y = np.array([3000,3250,3500,3750,4000,4250])
m=len(X1)

print(f'Lata pracy: {X1}')
print(f'Wynagrodzenie: {Y}')
print(f'Liczba próbek: {m}')

Lata pracy: [1 2 3 4 5 6]
Wynagrodzenie: [3000 3250 3500 3750 4000 4250]
Liczba próbek: 6


In [5]:
X1 = X1.reshape(m,1)
print(X1)
print(X1.shape)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
(6, 1)


In [6]:
bias = np.ones((m,1))
print(bias)
print(bias.shape)

[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]
(6, 1)


In [7]:
X = np.append(bias, X1, axis=1)
print(X)
print(X.shape)

[[1. 1.]
 [1. 2.]
 [1. 3.]
 [1. 4.]
 [1. 5.]
 [1. 6.]]
(6, 2)


###<a name='2'></a> Równanie normalne

In [9]:
# Mnożenie macierzy
np.dot(X.T, X)

array([[ 6., 21.],
       [21., 91.]])

In [10]:
# Macierz odwrotna powyższej macierzy
L = np.linalg.inv(np.dot(X.T,X))
L

array([[ 0.86666667, -0.2       ],
       [-0.2       ,  0.05714286]])

In [11]:
P = np.dot(X.T,Y)
P

array([21750., 80500.])

In [12]:
np.dot(L,P)

array([2750.,  250.])

In [13]:
# Końcowa postać modelu Y=2750 + 250X1

###<a name='4'></a> Regresja liniowa przy pomocy scikit-learn

In [14]:
from sklearn.linear_model import LinearRegression

regression = LinearRegression()
regression.fit(X1,Y)

print(regression.intercept_)
print(regression.coef_[0])

2750.0
250.0
