<a href="https://colab.research.google.com/github/jaworskamalgorzata99-GIT/Maching-Learning-Bootcamp/blob/main/unsupervised/dimensionality_reduction/03_pca_wine.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###Import bibliotek

In [18]:
import pandas as pd
import numpy as np
import plotly.graph_objects as go
import plotly.express as px

np.set_printoptions(precision=4, suppress=True, edgeitems=5, linewidth=200)

###Załadowanie danych

In [19]:
df_raw = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data', header=None)
df = df_raw.copy()
df.head()

0      1     2     3     4    5     6     7     8     9     10    11    12  \
0   1  14.23  1.71  2.43  15.6  127  2.80  3.06  0.28  2.29  5.64  1.04  3.92   
1   1  13.20  1.78  2.14  11.2  100  2.65  2.76  0.26  1.28  4.38  1.05  3.40   
2   1  13.16  2.36  2.67  18.6  101  2.80  3.24  0.30  2.81  5.68  1.03  3.17   
3   1  14.37  1.95  2.50  16.8  113  3.85  3.49  0.24  2.18  7.80  0.86  3.45   
4   1  13.24  2.59  2.87  21.0  118  2.80  2.69  0.39  1.82  4.32  1.04  2.93   

     13  
0  1065  
1  1050  
2  1185  
3  1480  
4   735

In [20]:
data = df.iloc[:,1:]
target = df.iloc[:,0]
data.head()

1     2     3     4    5     6     7     8     9     10    11    12  \
0  14.23  1.71  2.43  15.6  127  2.80  3.06  0.28  2.29  5.64  1.04  3.92   
1  13.20  1.78  2.14  11.2  100  2.65  2.76  0.26  1.28  4.38  1.05  3.40   
2  13.16  2.36  2.67  18.6  101  2.80  3.24  0.30  2.81  5.68  1.03  3.17   
3  14.37  1.95  2.50  16.8  113  3.85  3.49  0.24  2.18  7.80  0.86  3.45   
4  13.24  2.59  2.87  21.0  118  2.80  2.69  0.39  1.82  4.32  1.04  2.93   

     13  
0  1065  
1  1050  
2  1185  
3  1480  
4   735

In [21]:
target.value_counts()

0
2    71
1    59
3    48
Name: count, dtype: int64

###Podział danych na zbiór treningowy i testowy

In [27]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(data, target)

print(f'X_train shape: {X_train.shape}')
print(f'X_test shape: {X_test.shape}')

X_train shape: (133, 13)
X_test shape: (45, 13)


###Standaryzacja

In [28]:
print(X_train.shape)
print(X_test.shape)


(133, 13)
(45, 13)


In [29]:

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train_std = scaler.fit_transform(X_train)
X_test_std = scaler.transform(X_test)
X_train_std[:5]


array([[-0.853 , -0.6064, -0.2015,  1.5283, -0.828 , -0.2209,  0.312 ,  0.3955,  0.5117, -1.291 , -0.3442,  0.1535, -1.2971],
       [ 0.2442,  1.445 , -0.2379, -0.4971,  0.258 ,  0.4515,  0.4916, -0.2579,  0.0596, -0.3054, -0.6423,  0.4741, -0.2431],
       [-2.0637, -1.3833,  0.5267,  0.5156, -0.828 ,  0.1953, -0.1271,  0.5589, -0.3548, -0.8686,  0.5503, -0.5314, -1.0102],
       [ 1.4674,  1.4974,  0.3082, -0.092 ,  0.8373,  0.7876,  0.5116, -0.4213, -0.7127,  0.0818, -0.4294,  0.955 ,  1.0043],
       [-0.5882, -0.9032, -0.9296,  0.2262,  0.258 , -1.4054, -1.5542,  1.4574, -0.4301,  1.1202, -1.6646, -1.6389, -0.3678]])

###PCA

In [45]:
from sklearn.decomposition import PCA

#pca = PCA(n_components=0.9)
#lub
pca = PCA(n_components=3)
X_train_pca = pca.fit_transform(X_train_std)
X_test_pca = pca.transform(X_test_std)
X_train_pca.shape

(133, 3)

Wyjaśniona wariancja

In [46]:
results = pd.DataFrame(data={'explained_variance_ratio': pca.explained_variance_ratio_})
results['cumulative'] = results['explained_variance_ratio'].cumsum()
results['components'] = results.index + 1
results

explained_variance_ratio  cumulative  components
0                  0.352770    0.352770           1
1                  0.195434    0.548204           2
2                  0.109069    0.657272           3

In [47]:
fig = go.Figure(data=[go.Bar(x=results['components'], y=results['explained_variance_ratio'], name='explained_variance_ratio'),
                      go.Scatter(x=results['components'], y=results['cumulative'], name='cumulative')],
                layout=go.Layout(title=f'PCA - {pca.n_components_} components', width=950, template='plotly_dark'))
fig.show()

In [48]:
X_train_pca_df = pd.DataFrame(data=np.c_[X_train_pca, y_train], columns=['pca_1','pca_2','pca_3','target'])
X_train_pca_df.head()

pca_1     pca_2     pca_3  target
0 -0.795186 -1.792359  1.459807     2.0
1  0.274800  0.361963 -0.218731     1.0
2 -0.831618 -2.145974  1.305782     2.0
3  1.031349  1.736245 -0.109414     1.0
4 -2.951790  0.535249 -1.130193     3.0

In [49]:
px.scatter_3d(X_train_pca_df, x='pca_1', y='pca_2', z='pca_3', color='target', template='plotly_dark', width=950)

In [38]:
X_train_pca[:5]

array([[-0.7952, -1.7924,  1.4598],
       [ 0.2748,  0.362 , -0.2187],
       [-0.8316, -2.146 ,  1.3058],
       [ 1.0313,  1.7362, -0.1094],
       [-2.9518,  0.5352, -1.1302]])

In [39]:
X_test_pca[:5]

array([[-3.1776,  0.4045, -0.1728],
       [-3.7259,  1.5036, -0.223 ],
       [-1.5858, -0.5977,  2.0036],
       [ 3.3319,  1.0496, -0.4519],
       [-0.4237, -1.9996,  0.6285]])